### ISSUE TITLE
Post request common_headers ignored when asserting Content-Type header

### ISSUE THREAD

**Issue by matmar10** [kiranz/just-api#31]
# Example Test Case

```yml
meta:
  name: Testing headers
  enabled: true
  version: "1.0"
configuration:
  scheme: http
  host: 127.0.0.1
  port: 3027
  common_headers:
    - name: customsuiteheader
      value: custom-suite-header-value
    - name: content-type
      value: application/json
specs:
  - name: uses suite-level content-type header
    request:
      path: /echoJSONBodyResponse
      method: post
      payload:
          body:
              type: json
              content:
                  name: Kiran
    response:
        status_code: 200
```

# Actual Behavior

```
Request method is post,request body is provided but Content-Type header is not provided
```

# Expected Behavior

Suite-level common_headers should be checked when this assertion runs.
