### ISSUE TITLE
Suite custom_configuration from module ignores common_headers

### ISSUE THREAD

**Issue by matmar10** [kiranz/just-api#35]
# Steps to reproduce

```yaml
configuration:
  custom_configuration:
    run_type: module
    module:
      module_path: some-module.js
      function_name: suiteConfigSync
specs:
  - name: uses suite-level custom_configuration content-type header
    request:
      path: /echoJSONBodyResponse
      method: post
      payload:
          body:
              type: json
              content:
                  name: Kiran
    response:
        status_code: 200
```

```JavaScript
module.exports = {
  suiteConfigSync: function() {
    this.common_headers = [{
      name: 'content-type',
      value: 'application/json'
    }];
  }
};
```

# Actual Behavior

```
InvalidRequestHeaderError: Request method is post,request body is provided but Content-Type header is not provided
```

# Expected Behavior

`common_headers` should be honored
