### ISSUE TITLE
Enhancement: allow JSON pointer to schema within file

### ISSUE THREAD

**Issue by matmar10** [kiranz/just-api#37]
# Use Case

An OpenAPI (FKA Swagger) spec often contains multiple schema definitions, such as `#/components/responses/someResponseName` 

It would be very useful to reuse schema definitions from within the existing files, such as:

```
specs:
  - name: Some request
    ...
    response:
      json_schema:
        type: file
        $ref: schemas/openapi.json#/components/responses/NotFoundError
```

This would read the __dirname/schemas/openapi.json and extract the components.responses.NotFoundError property. 

I can probably submit a contribution for this but would like to collect thoughts to make sure I implement it correctly.
