### ISSUE TITLE
SSL error on reading https endpoint

### ISSUE THREAD

**Issue by mrcasablr** [kiranz/just-api#7]
Hi!

I get the following error when access a https endpoint 

```
Error: write EPROTO 140263490227968:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1407:SSL alert number 40

    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

My configuration looks like -
```
meta:
  name: GraphQL API
configuration:
  host: api.example.com
  scheme: https
  port: 8443
specs:
  - name: Get list of all users
    request:
      method: post
      path: /graphql
      headers:
        - name: content-type
          value: application/json
      payload:
        body:
          type: json
          content:
            query: >
                   {
                       getUser(id: "xxxx-xxxx-xxxx-xxxx-xxxxx70cc6d7"){
                        first_name
                        }
                    }
            variables: null
            operationName: null
    response:
      status_code: 200
      json_data:
        - path: $.data.getUser.first_name
          value: "John"
```

The server has a valid SSL certificate signed by a CA.
